# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0002_auto_20170813_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamuser',
            name='rank',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('1fbe9392-d6b6-4d37-96af-546bc4800a58'), max_length=200),
        ),
    ]
