# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=30)),
                ('port', models.IntegerField(default=0)),
                ('game', models.CharField(max_length=20)),
                ('gamemode', models.CharField(max_length=50)),
            ],
        ),
    ]
