# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('e9287275-ca4b-4890-aabc-47fd4fbca0b9'), max_length=200),
        ),
    ]
