# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('8f1218f6-d63c-4444-b646-73cb3800aa29'), max_length=200),
        ),
    ]
