# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0002_auto_20170814_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('5775a415-085b-4c8e-9b53-3ed65084b17a'), max_length=200),
        ),
    ]
