# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0002_auto_20170816_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steamuser',
            old_name='user_gpy_profile',
            new_name='gpy_profile',
        ),
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('90c9fabc-08cc-4d23-9e93-81fa96d835a3'), max_length=200),
        ),
    ]
