# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0003_auto_20170816_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SteamUserGpyProfile',
            new_name='GpyProfile',
        ),
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('84996ff5-dc41-4d5e-aead-b6a5edddce0e'), max_length=200),
        ),
    ]
