# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0003_auto_20170814_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('744a292c-fa90-4555-9fb9-817c6b2c2509'), max_length=200),
        ),
    ]
