# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0003_auto_20170815_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='steamid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('26e0a69f-2826-4bd7-a671-bdabff2b18a1'), max_length=200),
        ),
    ]
