# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0004_auto_20170815_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('3b40988e-fef6-43d2-b9d6-30bcaf699c67'), max_length=200),
        ),
    ]
