# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gpy_main', '0005_auto_20170815_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('011d8e13-3076-41dc-9f76-9800483c3671'), max_length=200),
        ),
    ]
