# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 01:14
from __future__ import unicode_literals

import apps.main.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171105_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='', upload_to=apps.main.models.announcement_image_path),
        ),
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('1de46e30-c2ec-46ac-ae13-343a5c622034'), max_length=200),
        ),
    ]
