# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171105_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ulxsecretkey',
            name='value',
            field=models.CharField(default=uuid.UUID('b96084d5-d593-42c8-90d7-6dae718470a9'), max_length=200),
        ),
    ]
